name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      SENDGRID_API_KEY: SG.test123
    services:
        sendgrid:
          image: ghashange/sendgrid-mock:1.9.0
          env:
            API_KEY: ${{ env.SENDGRID_API_KEY }}
          ports:
            - 3000:3000
    strategy:
      matrix:
        python-version: ["3.10.13", "3.11.5", "3.12.0", "3.13.2"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup the environment
        uses: ./.github/actions/build_env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check the linting
        run: poetry run python -m flake8 async_sendgrid

      - name: Check the format
        run: poetry run python -m black --check async_sendgrid

      - name: Check the typing
        run: poetry run python -m mypy async_sendgrid
      
      - name: Run tests
        run: poetry run python -m pytest --cov=async_sendgrid
        env:
          SENDGRID_API_KEY: ${{ env.SENDGRID_API_KEY }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}